In [0]:
import tensorflow as tf
import pandas as pd
from sklearn.model_selection import train_test_split

In [0]:
bank_data = pd.read_csv("./bank.csv")

In [3]:
bank_data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [4]:
bank_data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [5]:
bank_data.describe().T

count          mean  ...           75%          max
RowNumber        10000.0  5.000500e+03  ...  7.500250e+03     10000.00
CustomerId       10000.0  1.569094e+07  ...  1.575323e+07  15815690.00
CreditScore      10000.0  6.505288e+02  ...  7.180000e+02       850.00
Age              10000.0  3.892180e+01  ...  4.400000e+01        92.00
Tenure           10000.0  5.012800e+00  ...  7.000000e+00        10.00
Balance          10000.0  7.648589e+04  ...  1.276442e+05    250898.09
NumOfProducts    10000.0  1.530200e+00  ...  2.000000e+00         4.00
HasCrCard        10000.0  7.055000e-01  ...  1.000000e+00         1.00
IsActiveMember   10000.0  5.151000e-01  ...  1.000000e+00         1.00
EstimatedSalary  10000.0  1.000902e+05  ...  1.493882e+05    199992.48
Exited           10000.0  2.037000e-01  ...  0.000000e+00         1.00

[11 rows x 8 columns]

In [6]:
bank_data.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [0]:
bank_data = bank_data.drop(columns=['RowNumber','CustomerId','Surname'])

In [0]:
Y = bank_data.Exited

In [0]:
X = bank_data

In [12]:
X.dtypes

CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [13]:
bank_data.Exited.value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
X.iloc[:, 1] = labelencoder_x.fit_transform(X.iloc[:, 1]) #applying on Geography
X.head()

CreditScore  Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619          0  Female  ...               1        101348.88       1
1          608          2  Female  ...               1        112542.58       0
2          502          0  Female  ...               0        113931.57       1
3          699          0  Female  ...               0         93826.63       0
4          850          2  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [0]:
X.iloc[:, 2] = labelencoder_x.fit_transform(X.iloc[:, 2]) #applying on Gender


In [16]:
from keras.utils import to_categorical
encoded = pd.DataFrame(to_categorical(X.iloc[:, 1]))
#no need to encode Gender, as there are only two categories

X = pd.concat([encoded, X], axis = 1)

Using TensorFlow backend.


In [0]:
X = X.drop(['Geography', 0], axis = 1)
#x.head()

In [0]:
X_train,X_test,y_train,y_test= train_test_split(X,Y,test_size =0.3,random_state = 123)

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [0]:
#Initialize Sequential Graph (model)
model = tf.keras.Sequential()

#Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(tf.keras.layers.Dense(1, input_shape=(12,)))

#Compile the model - add Loss and Gradient Descent optimizer
model.compile(optimizer='sgd', loss='mse',metrics=['accuracy'])

In [71]:
y_train.shape

(7000,)

In [72]:
model.fit(X_train, y_train,batch_size=30)

Train on 7000 samples
7000/7000 [==============================] - 0s 47us/sample - loss: 0.2451 - acc: 0.8894


In [74]:
y_pred = model.predict(X_test)
y_pred

array([[ 0.05136438],
       [-0.0380989 ],
       [-0.05556943],
       ...,
       [-0.03969659],
       [ 0.00726223],
       [-0.14691858]], dtype=float32)

In [75]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_14 (Dense)             (None, 1)                 13        
Total params: 13
Trainable params: 13
Non-trainable params: 0
_________________________________________________________________


In [0]:
#from keras.optimizers import SGD
from tensorflow.keras.optimizers import SGD


In [0]:
from keras.models import Sequential
from keras.layers import Dense

In [0]:
# Initializing the ANN
classifier = Sequential()

In [0]:
classifier.add(Dense(activation = 'relu', input_dim = 12, units=6, kernel_initializer='uniform'))

In [0]:

classifier.add(Dense(activation = 'sigmoid', units=1, kernel_initializer='uniform'))

In [0]:

classifier.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [117]:

classifier.fit(X_train, y_train, batch_size=20, epochs=10)

Epoch 1/10
7000/7000 [==============================] - 0s 71us/step - loss: 0.0284 - acc: 1.0000
Epoch 2/10
7000/7000 [==============================] - 0s 71us/step - loss: 0.0242 - acc: 1.0000
Epoch 3/10
7000/7000 [==============================] - 0s 68us/step - loss: 0.0206 - acc: 1.0000
Epoch 4/10
7000/7000 [==============================] - 0s 70us/step - loss: 0.0177 - acc: 1.0000
Epoch 5/10
7000/7000 [==============================] - 0s 68us/step - loss: 0.0151 - acc: 1.0000
Epoch 6/10
7000/7000 [==============================] - 0s 69us/step - loss: 0.0130 - acc: 1.0000
Epoch 7/10
7000/7000 [==============================] - 0s 69us/step - loss: 0.0112 - acc: 1.0000
Epoch 8/10
7000/7000 [==============================] - 0s 71us/step - loss: 0.0096 - acc: 1.0000
Epoch 9/10
7000/7000 [==============================] - 0s 68us/step - loss: 0.0083 - acc: 1.0000
Epoch 10/10
7000/7000 [==============================] - 0s 68us/step - loss: 0.0071 - acc: 1.0000


In [118]:
classifier.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 6)                 78        
_________________________________________________________________
dense_8 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 7         
_________________________________________________________________
dense_10 (Dense)             (None, 6)                 12        
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 7         
Total params: 146
Trainable params: 146
Non-trainable params: 0
_________________________________________________________________


In [129]:
#Predicting the Test set results
y_pred_2 = classifier.predict(X_test)
#Threshold of 50%
y_pred_2 = (y_pred > 0.5)
y_pred_2

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [0]:
from sklearn.metrics import confusion_matrix

In [131]:
cm = confusion_matrix(y_test, y_pred_2)
cm

array([[2395,    0],
       [   0,  605]])